# Site settings

title: Herbert de Oliveira (Beto)
email: betooliveirame@icloud.com
description: "Um blog sobre tecnologia"
baseurl: ""
twitter_username: betooliveirame
github_username:  betoliveirame
paginate: 5

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .editorconfig
  - .git
  - LICENSE.md
  - README.md
  - docker-compose.yml
  - CNAME

nav:
  - title: Historico
    url: /archive

  - title: Sobre
    url: /about

tag_page_layout: tag_page
tag_page_dir: tag
